inherit_from: configs/agile/shapenet_grid32_depth_like_world.yaml
model:
  encoder_kwargs:
    n_blocks: 10
    hidden_dim: 64
    unet3d_kwargs:
      f_maps: 64
      in_channels: 64
      out_channels: 64
  decoder_kwargs:
    n_blocks: 10
    hidden_dim: 64
  c_dim: 64
training:
  out_dir: out/agile/big_model
