inherit_from: configs/agile/shapenet_grid32_depth_like_world.yaml
data:
  pointcloud_n: null
training:
  out_dir: out/agile/heterogeneous
  batch_size: 16
  batch_size_val: 16
  print_every: 20
  visualize_every: 4000
  validate_every: 2000
  max_iter: 200000