inherit_from: configs/agile/shapenet_grid32_depth_like_world.yaml
model:
  encoder_kwargs:
    unet3d_kwargs:
      in_channels: 64
      out_channels: 64
  c_dim: 64
training:
  out_dir: out/agile/more_features
