inherit_from: configs/pointcloud/shapenet_grid32_depth_like_upper.yaml
training:
  out_dir: out/pointcloud/shapenet_grid32_depth_like_world
  batch_size_val: 32
  in_world_coords: true
  print_every: 10
  visualize_every: 2000
  validate_every: 1000