inherit_from: configs/agile/shapenet_grid32_depth_like_world.yaml
data:
  classes: [ "02876657" ]
  path: data/ShapeNet/extra
  input_type: blenderproc
  path_prefix: "/home/matthias/Data2/datasets/shapenet/depth"
  pointcloud_n: null
  pointcloud_noise: 0.0001
  normalize: center
training:
  out_dir: out/agile/bottle/test
  batch_size: 8
  batch_size_val: 8
  print_every: 20
  visualize_every: 200
  validate_every: 100
  max_iter: 100000
generation:
  vis_n_outputs: 4