method: conv_onet
data:
  input_type: partial_pointcloud
  classes: null
  path: /home/matthias/Data2/datasets/shapenet/matthias/disn/core
  pointcloud_n: 3000
  pointcloud_noise: 0.005
  points_subsample: 2048
  points_file: uniform_random.npy
  points_iou_file: uniform_random.npy
  pointcloud_file: surface.npy
  pointcloud_chamfer_file: surface.npy
  voxels_file: 'model.binvox'
model:
  encoder: pointnet_local_pool
  encoder_kwargs:
    hidden_dim: 32
    plane_type: 'grid'
    grid_resolution: 32
    unet3d: true
    unet3d_kwargs:
      num_levels: 3
      f_maps: 32
      in_channels: 32
      out_channels: 32
  decoder: simple_local
  decoder_kwargs:
    sample_mode: bilinear # bilinear / nearest
    hidden_size: 32
    sdf: true
  c_dim: 32
training:
  pre_trained_weights: /home/matthias/Data/Ubuntu/git/convolutional_occupancy_networks/out/pointcloud/shapenet_grid32_sdf/model_best.pt
  out_dir: out/pointcloud/shapenet_grid32_partial_sdf
  batch_size: 32
  model_selection_metric: iou
  model_selection_mode: minimize
  print_every: 100
  visualize_every: 10000
  validate_every: 10000
  checkpoint_every: 2000
  backup_every: 10000
  n_workers: 8
  n_workers_val: 4
  max_iter: 60000
test:
  threshold: 0.0
  eval_mesh: true
  eval_pointcloud: false
  model_file: model_best.pt
generation:
  vis_n_outputs: 2
  refine: false
  upsampling_steps: 0
  resolution_0: 128
  use_sklearn: true
  n_x: 128
  n_z: 1
