method: conv_onet
data:
  input_type: partial_pointcloud
  part_ratio: 0.5
  classes: ["02876657"]
  path: /home/matthias/Data2/datasets/shapenet/matthias/disn/extra
  pointcloud_n: 3000
  pointcloud_noise: 0.005
  points_subsample: 2048
  points_file: surface_random.npy
  points_iou_file: surface_random.npy
  pointcloud_file: surface.npy
  pointcloud_chamfer_file: surface.npy
  voxels_file: 'model.binvox'
  occ_from_sdf: true
model:
  encoder: pointnet_local_pool
  encoder_kwargs:
    hidden_dim: 32
    plane_type: ['xz', 'xy', 'yz']
    plane_resolution: 64
    unet: True
    unet_kwargs:
      depth: 4
      merge_mode: concat
      start_filts: 32
  decoder: simple_local
  decoder_kwargs:
    sample_mode: bilinear # bilinear / nearest
    hidden_size: 32
  c_dim: 32
training:
  pre_trained_weights: https://s3.eu-central-1.amazonaws.com/avg-projects/convolutional_occupancy_networks/models/pointcloud/shapenet_3plane_partial.pt
  out_dir: out/pointcloud/shapenet_3plane_partial_occ_from_sdf_surface
  batch_size: 32
  model_selection_metric: iou
  model_selection_mode: maximize
  print_every: 100
  visualize_every: 1000
  validate_every: 1000
  checkpoint_every: 1000
  backup_every: 10000
  n_workers: 8
  n_workers_val: 4
test:
  threshold: 0.5
  eval_mesh: true
  eval_pointcloud: false
  model_file: model_best.pt
generation:
  vis_n_outputs: 10
  refine: false
  upsampling_steps: 0
  resolution_0: 128
  use_skimage: true
  n_x: 128
  n_z: 1
