inherit_from: configs/pointcloud/shapenet_grid32_depth_like_upper.yaml
training:
  pre_trained_weights: /home/matthias/Data/Ubuntu/git/convolutional_occupancy_networks/out/pointcloud/shapenet_grid32_depth_like_upper/model_100000.pt
  out_dir: out/pointcloud/shapenet_grid32_depth_like_world
  in_world_coords: true
