method: conv_onet
data:
  input_type: pointcloud
  classes: ["02876657", "02880940", "02946921", "03797390"]
  path: /home/matthias/Data2/datasets/shapenet/matthias/disn/extra
  pointcloud_n: 3000
  pointcloud_noise: 0.005
  points_subsample: 2048
  points_file: surface_random.npy
  points_iou_file: uniform_random.npy
  pointcloud_file: surface.npy
  pointcloud_chamfer_file: surface.npy
  voxels_file: 'model.binvox'
model:
  encoder: pointnet_local_pool
  encoder_kwargs:
    hidden_dim: 32
    plane_type: [ 'xz', 'xy', 'yz' ]
    plane_resolution: 64
    unet: true
    unet_kwargs:
      depth: 4
      merge_mode: concat
      start_filts: 32
  decoder: simple_local
  decoder_kwargs:
    sample_mode: bilinear # bilinear / nearest
    hidden_size: 32
    sdf: true
  c_dim: 32
training:
  pre_trained_weights:
  out_dir: out/pointcloud/shapenet_3plane_sdf_surface
  batch_size: 32
  model_selection_metric: loss
  model_selection_mode: minimize
  print_every: 100
  visualize_every: 10000
  validate_every: 1000
  checkpoint_every: 2000
  backup_every: 10000
  n_workers: 8
  n_workers_val: 4
  max_iter: 20000
test:
  threshold: 0.0
  eval_mesh: true
  eval_pointcloud: false
  model_file: model_best.pt
generation:
  vis_n_outputs: 2
  refine: false
  upsampling_steps: 0
  resolution_0: 128
  n_x: 128
  n_z: 1
