inherit_from: configs/pointcloud/shapenet_grid32_depth_like_world_center.yaml
data:
  classes: [ "02876657" ]
  path: data/ShapeNet/extra
  input_type: blenderproc
  path_prefix: /home/matthias/Data2/datasets/shapenet/depth
training:
  out_dir: out/bottle/blenderproc
  print_every: 10
  visualize_every: 1000
  validate_every: 1000
  checkpoint_every: 1000
  backup_every: 1000
  max_iter: 20000
generation:
  vis_n_outputs: 10