inherit_from: configs/pointcloud/shapenet_grid32_partial.yaml
data:
  classes: [ "02876657" ]
  path: data/ShapeNet/extra
  part_ratio: [0.4, 0.6]
  normalize: center
  voxels_file: null
training:
  out_dir: out/bottle/partial_world
  in_cam_coords: true
  print_every: 10
  visualize_every: 1000
  validate_every: 1000
  checkpoint_every: 1000
  backup_every: 1000
  max_iter: 20000
generation:
  vis_n_outputs: 10