inherit_from: configs/pointcloud/shapenet_grid32.yaml
generation:
  generation_dir: generation_pretrained
test:
  model_file: /home/matthias/Data/Ubuntu/git/convolutional_occupancy_networks/out/pointcloud/shapenet_grid32_partial/model_best.pt
